name: Getting Married In Sweden
favicon: null
layout_spectrum: 0.73051
typography_spectrum: 0.7764317714609206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3e9e6'
    - '#c2c3c5'
    - '#656b7e'
    - '#000000'
    - '#2f2a43'
  brandStrength: 0.5
  lightness: 0.7915534169878811
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
