name: Getting Married In Sweden
favicon: null
layout_spectrum: 0.73051
typography_spectrum: 1
title: Getting Married In Sweden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f5f1'
    - '#ebd5cc'
    - '#9e7b6e'
    - '#563915'
    - '#385b72'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
