name: Getting Married In Sweden
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7606
title: Getting Married In Sweden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1d1d1'
    - '#f3f3f3'
    - '#ededed'
    - '#e5e5e5'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
